data_prep:
  version: "1.0"
  dataset_name: "bank_marketing_term_deposit_prediction"
  onehot_encode_columns: ["job", "education", "poutcome"]
  label_encode_columns: ["marital", "default", "housing", "loan", "contact", "month"]

feature_prep:
  enable_duration_features: true
  enable_balance_features: true
  enable_campaign_features: true
  enable_seasonal_features: true
  enable_previous_outcome_features: true

model_evaluation:
  cv_folds: 5
  stratified: true
  primary_metric: "roc_auc"
  random_state: 42

model:
  model_type: "gradient_boosting"
  model_params:
    n_estimators: 200
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    max_features: "sqrt"
    random_state: 42



